name       : xmlsec1
version    : 1.2.27
release    : 3
source     :
    - https://github.com/lsh123/xmlsec/archive/xmlsec-1_2_27.tar.gz : 7465b5cffb0cedb2f350d727debfa86598218d58b2edebc3ce279f5fca07bd0d
license    : MIT
component  : security.library
libsplit   : no
summary    : Library providing support for "XML Signature" and "XML Encryption" standards
description: |
    XML Security Library is a C library based on LibXML2  and OpenSSL.
    The library was created with a goal to support major XML security
    standards "XML Digital Signature" and "XML Encryption".
builddeps  :
    - pkgconfig(gnutls)
    - pkgconfig(libexslt)
    - pkgconfig(nss)
    - libgcrypt-devel
patterns   :
    - devel :
        - /usr/bin/xmlsec1-config
        - /usr/lib64/xmlsec1Conf.sh
        - /usr/share/doc/*
        - /usr/share/man/man1/xmlsec1-config.1
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    # %make check
