name       : xmlsec1
version    : 1.2.26
release    : 2
source     :
    - https://www.aleksey.com/xmlsec/download/xmlsec1-1.2.26.tar.gz : 8d8276c9c720ca42a3b0023df8b7ae41a2d6c5f9aa8d20ed1672d84cc8982d50
license    : MIT
component  : security.library
libsplit   : no
summary    : Library providing support for "XML Signature" and "XML Encryption" standards
description: |
    XML Security Library is a C library based on LibXML2  and OpenSSL.
    The library was created with a goal to support major XML security
    standards "XML Digital Signature" and "XML Encryption".
builddeps  :
    - pkgconfig(gnutls)
    - pkgconfig(libexslt)
    - pkgconfig(nss)
patterns   :
    - devel :
        - /usr/bin/xmlsec1-config
        - /usr/lib64/xmlsec1Conf.sh
        - /usr/share/doc/*
        - /usr/share/man/man1/xmlsec1-config.1
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
